services:

  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=ROOT-Password2025!
      - MARIADB_USER=userbd
      - MARIADB_PASSWORD=Password2025!
      - MARIADB_DATABASE=mabase
    ports:
      - "3306:3306"

  monapache:
    image: bluz0/monapache:latest
    ports:
      - "80:80"
    volumes:
      - ./monapache:/var/www/html  # Mount the local directory to the container


  monubuntu:
    image: bluz0/monubuntu:latest

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb  # Connexion automatique à MariaDB
    ports:
      - "8080:80"  # Port d'accès à phpMyAdmin


